### ISSUE TITLE
Create a "Sendable" and a "Receivable" protocol

### ISSUE THREAD

**Issue by MatthiasKreileder** [vapor/socks#24]
This issue comprises the following steps
- [ ] Create a "Sendable" protocol + extension which defines a function that serializes an object (so that it can be passed to the Socket write function)
- [ ] Create a "Receivable" protocol + extension which defines a function that deserializes an object (so that it can be created from the bytes received by a socket read call)

**Comment by banxi1988** [comment]
Hi, I don't think that socks should include this features.
socks has already did well as a Socket Library. 
anyone need the feature can have their own extensions.
