### ISSUE TITLE
Making example executables private

### ISSUE THREAD

**Issue by tannernelson** [vapor/socks#40]
Is there something we could do to make the example modules not show up in Xcode or be built during `swift build`?

Maybe .gitignore?

It's a bit overwhelming both during the build process and in Xcode.

![screen shot 2016-06-06 at 10 17 38 am](https://cloud.githubusercontent.com/assets/1342803/15824997/f5b3169e-2bcf-11e6-9e2b-012fe806ae69.png)

**Comment by czechboy0** [comment]
😞 I know, it is pretty annoying. There was a proposal for making certain targets internal-only (something you'd specify in the project's Package.swift). I guess bring it up in the mailing list? I'll back you as it does get overwhelming when you have more dependencies with executables.
